<header>
	<h1 class="logo"><a href="/" class="btn_alpha"><img src="/common/images/logo.png" alt="Farmers Forest Group"></a></h1>
	<nav class="nav_global" id="nav_global">
		<ul>
			<li><a href="/"><p>Projects</p></a></li>
			<li><a href="/info/"><p>Configuration</p></a></li>
			<li><a href="/company/"><p>Message Review</p></a></li>
		</ul>
	</nav>
	<figure class="menu" id="menu">
		<a class="menu_trigger">
			<span></span>
			<span></span>
			<span></span>
		</a>
	</figure>
</header>